export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_ALL_RESTAURANT_LOADING = 'GET_ALL_RESTAURANT_LOADING';
export const GET_ALL_RESTAURANT_SUCCESS = 'GET_ALL_RESTAURANT_SUCCESS';
export const GET_ALL_RESTAURANT_FAILED = 'GET_ALL_RESTAURANT_FAILED';

export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const VERIFY_OTP_LOADING = 'VERIFY_OTP_LOADING';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

export const NEW_PASSWORD_LOADING = 'NEW_PASSWORD_LOADING';
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS';
export const NEW_PASSWORD_FAILED = 'NEW_PASSWORD_FAILED';

// PopularRestaurant
export const POPULAR_RESTAURENT_LOADING = 'POPULAR_RESTAURENT_LOADING';
export const POPULAR_RESTAURENT_SUCCESS = 'POPULAR_RESTAURENT_SUCCESS';
export const POPULAR_RESTAURENT_FAILED = 'POPULAR_RESTAURENT_FAILED';

// GetAllUser
export const GET_ALL_USER_LOADING = 'GET_ALL_USER_LOADING';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED';

// GetAllUser
export const CREATE_RESTAURANT_LOADING = 'CREATE_RESTAURANT_LOADING';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
export const CREATE_RESTAURANT_FAILED = 'CREATE_RESTAURANT_FAILED';
// Delete Restaurant
export const DELETE_RESTAURANT_LOADING = 'DELETE_RESTAURANT_LOADING';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';
export const DELETE_RESTAURANT_FAILED = 'DELETE_RESTAURANT_FAILED';
// GetAllReservation
export const GET_ALL_RESERVATION_LOADING = 'GET_ALL_RESERVATION_LOADING';
export const GET_ALL_RESERVATION_SUCCESS = 'GET_ALL_RESERVATION_SUCCESS';
export const GET_ALL_RESERVATION_FAILED = 'GET_ALL_RESERVATION_FAILED';
//CreateTable
export const CREATE_TABLE_LOADING = 'CREATE_TABLE_LOADING';
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILED = 'CREATE_TABLE_FAILED';
// Deleteuser
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
// userEdit
export const USER_EDIT_LOADING = 'USER_EDIT_LOADING';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';
// ShowProfileData
export const SHOW_PROFILE_DATA_LOADING = 'SHOW_PROFILE_DATA_LOADING';
export const SHOW_PROFILE_DATA_SUCCESS = 'SHOW_PROFILE_DATA_SUCCESS';
export const SHOW_PROFILE_DATA_FAILED = 'SHOW_PROFILE_DATA_FAILED';
